### ISSUE TITLE
Bug report feature malfunctions

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/dvpn-web#512]
Once new bug report is submitted via NodeUI, Intercom should should initiate a new chat which evokes bot communication. Currently, no chats are being added into the Intercom's welcome screen.

**Comment by Guillembonet** [comment]
After discussions and support query we found that the bot does not reply to conversations created via API. So we will do the following:
1. Have the email as mandatory info during the bug report so support can contact him in case he closes the chat
2. (optional) Somehow let user know that this is needed so they don't need to keep the chat open since they provided email
3. Call API as we do know to generate bug report with node logs which:
    3.1. Uploads node logs and makes them accessible from mystnodes for support
    3.2. Creates a Github issue as it is done now
    3.3. Returns the message that has to be sent to intercom (which contains description and link to node logs)
4. Open intercom message window with the message from step 3.3 pre-filled and the user just needs to click send. This is [supported by Intercom Javascript API already](https://developers.intercom.com/installing-intercom/web/methods/#pre-populate-messages), but we will probably need some additional logic to [set tags to that user](https://developers.intercom.com/installing-intercom/web/methods/#ids--data) as we do now in the backend to set things like node identity, ... 
5. Intercom AI bot will be able to automatically reply
